-- Insertar los Planes SaaS base
INSERT INTO planes_saas (nombre, precio_mensual, limite_propiedades, permite_ia) VALUES
('Básico', 30000.00, 50, 0),
('Profesional', 70000.00, -1, 1),
('Enterprise', 0.00, -1, 1); -- Precio 0 temporal (requiere cotización personalizada)

-- Pre-cargar los Socios Inmobiliarios de la CIM (Todos inician en Plan Básico por defecto)
INSERT INTO socios_inmobiliarios (nombre_comercial, id_plan_actual) VALUES
('ARAUCARIA PROPIEDADES', 1), ('ARQUIN', 1), ('AZUL PROPIEDADES (JUAN GONZALEZ)', 1),
('BERGOTTINI BIENES RAICES', 1), ('CARLES', 1), ('CARRAFA FLORES INMOBILIARIA', 1),
('CELMAN PROPIEDADES', 1), ('CHALANCZUK PROPIEDADES', 1), ('CHIOFALO & NADICH', 1),
('CORA CAMPOS', 1), ('DAVIÑA PROPIEDADES', 1), ('DEL OESTE INMUEBLES', 1),
('DELLAPIERRE', 1), ('FERNANDEZ INMOBILIARIA', 1), ('FERREIRA INMUEBLES', 1),
('FIDANZA INMOBILIARIA', 1), ('FORESTAL LA RAMA', 1), ('FUENTES PROPIEDADES', 1),
('G30 ESTUDIO INMOBILIARIO', 1), ('GARUPA PROPIEDADES', 1), ('GAUTO FECHNER INMOBILIARIA', 1),
('GIMENEZ & GIMENES INMOBILIARIA', 1), ('GRACIELA ARCE', 1), ('GUAYRA PROPIEDADES', 1),
('GUTLEBER PROPIEDADES', 1), ('GYS PROPIEDADES', 1), ('HITO INMOBILIARIA', 1),
('HOSLVAK PROPIEDADES', 1), ('IGUAZU INMUEBLES', 1), ('INGENIERO RESEK', 1),
('INMOBILIARIA SITIOS', 1), ('INNOVA INMOBILIARIA', 1), ('IVO GÔTZ', 1),
('JANIEL PROPIEDADES', 1), ('KAMADA INMOBILIARIA', 1), ('KUNZ PROPIEDADES', 1),
('LA CAPITAL PROPIEDADES', 1), ('LATINA S.A.', 1), ('LILIANA DURAN PROPIEDADES', 1),
('LOSAVIO & FULKET PROPIEDADES', 1), ('LOSAVIO DANIEL', 1), ('MANECO PROPIEDADES', 1),
('MARCELO MARINI INVERSIONES INMOBILIARIAS', 1), ('MARIA BOWER', 1), ('MELINA ROMERO INMOBILIARIA', 1),
('MERCEDES BONETTI INMOBILIARIA', 1), ('MIRTA MARCON INMOBILIARIA', 1), ('MISIONES INMOBILIARIA', 1),
('MONICA FOGELER INMOBILIARIA', 1), ('MONSU PROPIEDADES', 1), ('MyM PROPIEDADES', 1),
('NEXOS INMOBILIARIA', 1), ('NIELLA PROPIEDADES', 1), ('ORTIZ INMOBILIARIA', 1),
('P.O.E.A.', 1), ('PLATINIUM INMOBILIARIA', 1), ('RAICES INMOBILIARIA (MACIEL, ELDORADO)', 1),
('RAICES INMOBILIARIA (MARCO W.)', 1), ('RAUL CARRIZO INMOBILIARIA', 1), ('RIMA PROPIEDADES', 1),
('ROBLES PROPIEDADES', 1), ('RYS PROPIEDADES', 1), ('SAMUDIO HALLEY AIDA', 1),
('SEDKO PROPIEDADES', 1), ('SOLARI INMOBILIARIA', 1), ('SONIA PEREYRA INMOBILIARIA', 1),
('SOSA PROPIEDADES', 1), ('TEIJEIRO PROPIEDADES', 1), ('ULISES VALLARO INMOBILIARIA', 1),
('V PROPIEDADES', 1), ('VANINA PAULUK INMOBILIARIA', 1), ('VIBA PROPIEDADES', 1),
('ZAPANI PROPIEDADES', 1), ('ZUNY FERNANDEZ INMOBILIARIA', 1), ('SINGULAR', 1);